# Ahmed Abd-Elsalam Muhammed Afify
___
# Home 3&4:


## Practical_1 

In [1]:
import numpy as np

In [2]:
def matrix_2():
    arr = np.zeros((2,2))
    try:
        for i in range(2):
            for j in range(2):
                element = input(f'input element ({i+1},{j+1}): ')
                arr[[i],[j]] = element
        return arr
    except:
        raise Exception('Invalid input, please insert a numeric value')

In [3]:
def determinant_2(A):
    determinant = (A[[0],[0]]*A[[1],[1]])-(A[[0],[1]]*A[[1],[0]])
    return determinant[0]

In [4]:
def flip_2(A):
    A[[0],[0]], A[[1],[1]] = A[[1],[1]], A[[0],[0]]
    A[[0],[1]] = A[[0],[1]]*(-1)
    A[[1],[0]] = A[[1],[0]]*(-1)
    return A

In [5]:
def inverse_2():
    A = matrix_2()
    A = flip_2(A)
    Deter = determinant_2(A)
    
    inverse = np.round(A/Deter,decimals=2)
    return inverse

In [6]:
a = inverse_2()

input element (1,1): -3
input element (1,2): -2
input element (2,1): 3
input element (2,2): 3


In [7]:
a 

array([[-1.  , -0.67],
       [ 1.  ,  1.  ]])

___
## Practical_2

In [8]:
def matrix():
    n = input('Numer of rows = ')
    m = input('Number of columns = ')
    try:
        A = np.zeros((int(n),int(m)))
        for i in range(int(n)):
            for j in range(int(m)):
                element = input(f'element {i+1},{j+1} = ')
                A[[i],[j]] = int(element)
        return A
    except:
        return 'Input Error, insert a valid numeric input'

In [9]:
def vector():
    n = input('Numer of rows = ')
    try:
        B = np.zeros((int(n),1))
        for i in range(int(n)):
            element = input(f'element {i+1},1 = ')
            B[[i],0] = element
        return B
    except:
        return 'Input Error, insert a valid numeric input'

In [10]:
def check_dimensions(A,B):
    if len(B) != len(A):
        raise Exception('Input error, Matrix-B is not of the same dimension of A')

    for i in range(len(B)):
        if isinstance(B[i],list):
            raise Exception('Input error, Matrix-B is not a column vector')

In [11]:
def check_squared(A):
    for i in range(len(A)):
            if len(A[i]) != len(A):
                raise Exception('Input error, Matrix-A should be a square matrix (NxN)')

In [12]:
def calc_determinant(A):
    determinant = np.linalg.det(A)
    return determinant

In [13]:
def minor_coef(A, i, j):
    return np.delete(np.delete(A,i,0),j,1)

In [14]:
def minors(A):
    m = np.zeros((3,3))
    for i in range(len(A)):
        for j in range(len(A[i])):
            mat = minor_coef(A,i,j)
            value = (mat[0][0]*mat[1][1] - mat[0][1]*mat[1][0])
            m[[i],[j]] = value
    return m

In [15]:
def cofactors(A):
    n,m = A.shape[0], A.shape[1]
    cofactor = [1]*(n*m)
    sign = 1
    for i in range(len(cofactor)):
        cofactor[i] *= sign
        sign *= -1
    
    cofactor = np.array(cofactor)
    cofactor = cofactor.reshape(n,m)
    A = A*cofactor
    return A

In [16]:
def transpose(A):
    return A.T

In [17]:
def inverse(A,d):
    A_inverse = A/d
    return A_inverse

In [18]:
def solution():
    A = matrix()
    B = vector()
    check_dimensions(A,B)
    check_squared(A)
    Deter = calc_determinant(A)
    A = minors(A)
    A = cofactors(A)
    A = transpose(A)
    A = inverse(A,Deter)
    
    solution = np.round(A@B,decimals=2)
    return solution

In [19]:
x = solution()

Numer of rows = 3
Number of columns = 3
element 1,1 = 1
element 1,2 = 0
element 1,3 = -1
element 2,1 = 0
element 2,2 = 1
element 2,3 = -1
element 3,1 = 4
element 3,2 = 0
element 3,3 = -3
Numer of rows = 3
element 1,1 = -11
element 2,1 = 11
element 3,1 = 10


In [20]:
x

array([[43.],
       [65.],
       [54.]])

In [21]:
def inverse_alone():
    A = matrix()
    Deter = calc_determinant(A)
    minor = minors(A)
    cofactor = cofactors(minor)
    A_T = transpose(cofactor)
    A_inv = A_T/Deter

    return np.round(A_inv,decimals=2)

In [22]:
def solution_alone():
    A = inverse_alone()
    B = vector()
    check_dimensions(A,B)
    check_squared(A)
    
    solution = np.round(A@B,decimals=2)
    return solution

In [23]:
y = solution_alone()

Numer of rows = 3
Number of columns = 3
element 1,1 = 1
element 1,2 = 0
element 1,3 = -1
element 2,1 = 0
element 2,2 = 1
element 2,3 = -1
element 3,1 = 4
element 3,2 = 0
element 3,3 = -3
Numer of rows = 3
element 1,1 = -11
element 2,1 = 11
element 3,1 = 10


In [24]:
y

array([[43.],
       [65.],
       [54.]])

In [25]:
inv = inverse_alone()

Numer of rows = 3
Number of columns = 3
element 1,1 = 1
element 1,2 = 0
element 1,3 = -1
element 2,1 = 0
element 2,2 = 1
element 2,3 = -1
element 3,1 = 4
element 3,2 = 0
element 3,3 = 3


In [26]:
inv

array([[ 0.43, -0.  ,  0.14],
       [-0.57,  1.  ,  0.14],
       [-0.57, -0.  ,  0.14]])