# LAB 1: Matrix and Vector Computations in python

In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Apply linear transformation.


# First: you should run this cell

In [1]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import matplotlib.pyplot as plt

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [43]:
#type your code here:
S = np.array([[5]])
V = np.array([[5],[-2],[4]])
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[1,2],[3,4],[5,6]])

b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [44]:
#type your code here:
print('type(S) = ',type(S))
print('type(V) = ',type(V))
print('type(A) = ',type(A))

type(S) =  <class 'numpy.ndarray'>
type(V) =  <class 'numpy.ndarray'>
type(A) =  <class 'numpy.ndarray'>


c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [45]:
#type your code here:
print('S.shape = ', S.shape)
print('V.shape = ', V.shape)
print('A.shape = ', A.shape)
print('B.shape = ', B.shape)
print('C.shape = ', C.shape)

S.shape =  (1, 1)
V.shape =  (3, 1)
A.shape =  (3, 3)
B.shape =  (2, 3)
C.shape =  (3, 2)


d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [46]:
#type your code here:
print('A[2,1] = ',A[2,1])
A[2,1] = 10
print('A = \n', A)

A[2,1] =  8
A = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [47]:
#type your code here:
print('A[:, [1]] = \n' ,A[:, [1]])
print('B[[1],:] = \n', B[[1],:])

A[:, [1]] = 
 [[ 2]
 [ 5]
 [10]]
B[[1],:] = 
 [[4 5 6]]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [48]:
#type your code here:
print('np.eye(4) = \n', np.eye(4),'\n')
print('np.zeros(3) = \n', np.zeros(3),'\n')
print('np.zeros((3, 1)) = \n', np.zeros((3, 1)),'\n')
print('np.zeros((3, 5)) = \n',np.zeros((3, 5)),'\n')
print('np.ones((2, 3)) = \n',np.ones((2, 3)),'\n')
print('np.diag([4, 5, 6, 7]) = \n',np.diag([4, 5, 6, 7]),'\n')

np.eye(4) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

np.zeros(3) = 
 [0. 0. 0.] 

np.zeros((3, 1)) = 
 [[0.]
 [0.]
 [0.]] 

np.zeros((3, 5)) = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

np.ones((2, 3)) = 
 [[1. 1. 1.]
 [1. 1. 1.]] 

np.diag([4, 5, 6, 7]) = 
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]] 



# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [51]:
#type your code here:
v1 = np.array([[1],[2],[7],[4]])
v2 = np.array([[4],[3],[6],[8]])
print('v1 = \n',v1,'\n')
print('v2 = \n',v2,'\n')
print('v1 + v2 = \n',v1+v2,'\n')
print('v1 - v2 = \n',v1-v2,'\n')
print('3*v1 = \n',3*v1,'\n')
print('v1 / v2 = \n',v1/v2,'\n')

v1 = 
 [[1]
 [2]
 [7]
 [4]] 

v2 = 
 [[4]
 [3]
 [6]
 [8]] 

v1 + v2 = 
 [[ 5]
 [ 5]
 [13]
 [12]] 

v1 - v2 = 
 [[-3]
 [-1]
 [ 1]
 [-4]] 

3*v1 = 
 [[ 3]
 [ 6]
 [21]
 [12]] 

v1 / v2 = 
 [[0.25      ]
 [0.66666667]
 [1.16666667]
 [0.5       ]] 



b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [58]:
#type your code here:
print('Using numpy.dot = \n', np.dot(v1.T,v2),'\n')
print('Using numpy.matmul = \n', np.matmul(v1.T,v2),'\n')
print('Using @ = \n', (v1.T@v2))

Using numpy.dot = 
 [[84]] 

Using numpy.matmul = 
 [[84]] 

Using @ = 
 [[84]]


c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [59]:
#type your code here:
print('length of v1 Using numpy.linalg.norm = \n',np.linalg.norm(v1), '\n')
print('length of v2 Using numpy.linalg.norm = \n',np.linalg.norm(v2), '\n')
print('length of v1 Using the dot product and numpy.sqrt = \n',np.sqrt(np.dot(v1.T,v1)), '\n')
print('length of v2 Using the dot product and numpy.sqrt = \n',np.sqrt(np.dot(v2.T,v2)), '\n')

length of v1 Using numpy.linalg.norm = 
 8.366600265340756 

length of v2 Using numpy.linalg.norm = 
 11.180339887498949 

length of v1 Using the dot product and numpy.sqrt = 
 [[8.36660027]] 

length of v2 Using the dot product and numpy.sqrt = 
 [[11.18033989]] 



d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [60]:
#type your code here:
u = np.array([[3],[2],[-1],[4]])
v = np.array([[1],[-1],[1],[0]])
print('u.T @ v = \n', u.T @ v )

u.T @ v = 
 [[0]]


# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$

In [12]:
#type your code here:


u =
 [[2]
 [7]
 [2]]

v =
 [[8]
 [2]
 [4]]

A =
 [[7 3 5]
 [4 6 2]]

B =
 [[0 6 4]
 [2 3 0]]

A + B =
 [[7 9 9]
 [6 9 2]]

B + A =
 [[7 9 9]
 [6 9 2]]

3A =
 [[21  9 15]
 [12 18  6]]

6B =
 [[ 0 36 24]
 [12 18  0]]

2(3B) =
 [[ 0 36 24]
 [12 18  0]]

6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]



In [61]:
u = np.array([[2],[7],[2]])
v = np.array([[8],[2],[4]])
A = np.array([[7,3,5]],[4,6,2])
B = np.array([[0,6,4],[2,3,0]])
print('u = \n',u,'\n')

TypeError: Field elements must be 2- or 3-tuples, got '4'

b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [13]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4: Linear Transformation

Declare a vector $v = \begin{bmatrix} 5  \\ -2 \\ \end{bmatrix}$

a) Rotations: Generate a matrix Q and Let Q act on the vector

$Q = \begin{bmatrix} cos(\theta) & -sin(\theta)   \\ sin(\theta) & cos(\theta)    \\ \end{bmatrix}$ where $\theta = pi / 6$

- Repeat with $\theta = -pi/3$
- Use [matplotlib.pyplot.quiver](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html) to plot the vectors. Ex: `plt.quiver(v1[0], v1[1], angles='xy', scale_units='xy', scale=1, color='red', alpha=1)`
- Describe in words how the vector has changed.


In [ ]:
#type your code here:


b) Dilations: Generate a matrix D by

$D = \begin{bmatrix} r & 0   \\ 0 & 1/r    \\ \end{bmatrix}$ where $r = 0.9$

- Repeat with $r = 0.8$
- Use [matplotlib.pyplot.quiver](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html) to plot the vectors
- Describe in words how the vector has changed.

In [ ]:
#type your code here:


c) Shearing Transformations: Generate a matrix T by
$T = \begin{bmatrix} 1 & t   \\ 0 & 1    \\ \end{bmatrix}$ where $t = 0.5$

- Repeat with $t = -0.5$
- Use [matplotlib.pyplot.quiver](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html) to plot the vectors
- Describe in words how the vector has changed.

In [ ]:
#type your code here:
