In [2]:
import numpy as np

In [80]:
def matrix():
    n = input('Numer of rows = ')
    m = input('Number of columns = ')
    try:
        A = np.zeros((int(n),int(m)))
        #A = [[0]*int(n)]*int(m)
        for i in range(int(n)):
            for j in range(int(m)):
                element = input(f'element {i},{j} = ')
                A[[i],[j]] = int(element)

        return A
    except:
        print('Error')

In [81]:
def vector():
    n = input('Numer of rows = ')
    try:
        B = np.zeros((int(n),1))
        for i in range(int(n)):
            element = input(f'element {i},1 = ')
        return B
    except:
        return 'Input Error'

In [18]:
def check_dimensions(A,B):
    if len(B) != len(A):
        raise Exception('Input error, Matrix-B is not of the same dimension of A')

    for i in range(len(B)):
        if isinstance(B[i],list):
            raise Exception('Input error, Matrix-B is not a column vector')

In [77]:
A


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
check_dimensions([[1,2,3],[4,5,6],[7,8,9]],[1,2,3])

In [20]:
def check_squared(A):
    for i in range(len(A)):
            if len(A[i]) != len(A):
                raise Exception('Input error, Matrix-A should be a square matrix (NxN)')

In [38]:
A = [[1,2,3],[4,5,6],[7,8,9]]

In [27]:
def calc_determinant(A):
    determinant = np.linalg.det(A)
    return determinant

In [28]:
calc_determinant([[1,2,3],[4,5,6],[7,8,9]])

-9.51619735392994e-16

In [24]:
3%3

0

In [36]:
def minor_coef(A, i, j):
    return [row[: j] + row[j+1:] for row in (A[: i] + A[i+1:])]

In [37]:
getcofactor([[1,2,3],[4,5,6],[7,8,9]],0,1)

[[4, 6], [7, 9]]

In [78]:
def minors(A):
    lst = []
    for i in np.nditer(A):
        lst.append(i)
    m = np.zeros((3,3))
    for i in range(len(A)):
        for j in range(len(A[i])):
            mat = minor_coef(A,i,j)
            value = (mat[0][0]*mat[1][1] - mat[0][1]*mat[1][0])
            m[[i],[j]] = value
    return m

In [79]:
minors([[1,5,3],[4,5,6],[7,8,9]])

array([[ -3.,  -6.,  -3.],
       [ 21., -12., -27.],
       [ 15.,  -6., -15.]])

In [86]:

def cofactors(A):
    m = np.array([[1,-1,1],[-1,1,-1],[1,-1,1]])
    A = A*m
    return A

In [33]:
A = np.array([[1,5,3],[4,5,6],[7,8,9]])

In [88]:
e = cofactors(A)

In [89]:
e

array([[ 1, -5,  3],
       [-4,  5, -6],
       [ 7, -8,  9]])

In [91]:
def transpose(A):
    return A.T

In [93]:
transpose(e)

array([[ 1, -4,  7],
       [-5,  5, -8],
       [ 3, -6,  9]])

In [13]:
def cofactors(A):
    n,m = A.shape[0], A.shape[1]
    cofactor = [1]*(n*m)
    sign = 1
    for i in range(len(cofactor)):
        cofactor[i] *= sign
        sign *= -1
    
    cofactor = np.array(cofactor)
    cofactor = cofactor.reshape(n,m)
    A = A*cofactor
    return A

In [14]:
e = cofactors(A)

In [10]:
n = [1]*5*3

In [12]:
print(type(n))

<class 'list'>


In [15]:
e

array([[ 1, -5,  3],
       [-4,  5, -6],
       [ 7, -8,  9]])

In [16]:
def matrix():
    n = input('Numer of rows = ')
    m = input('Number of columns = ')
    try:
        A = np.zeros((int(n),int(m)))
        for i in range(int(n)):
            for j in range(int(m)):
                element = input(f'element {i+1},{j+1} = ')
                A[[i],[j]] = int(element)
        print(A)
        return A
    except:
        return 'Input Error, insert a valid numeric input'

In [17]:
def minor_coef(A, i, j):
    return [row[: j] + row[j+1:] for row in (A[: i] + A[i+1:])]

In [26]:
def minors(A):
    m = np.zeros((3,3))
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            mat = minor_coef(A,i,j)
            value = (mat[0][0]*mat[1][1] - mat[0][1]*mat[1][0])
            print(value)
            m[[i],[j]] = value
            
    print(m)
    return m

In [19]:
A = matrix()

Numer of rows = 3
Number of columns = 3
element 1,1 = 1
element 1,2 = 0
element 1,3 = 1
element 2,1 = 0
element 2,2 = 1
element 2,3 = 1
element 3,1 = 1
element 3,2 = 1
element 3,3 = 1
[[1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 1.]]


In [20]:
print(type(A))

<class 'numpy.ndarray'>


In [27]:
m = minors(A)

ValueError: operands could not be broadcast together with shapes (0,3) (2,3) 

In [40]:
e = minor_coef(A, 0, 1)

In [36]:
A = [1,5,3,4,5,6,7,8,9]

In [39]:
A[: 1] + A[1+1:]

[[1, 2, 3], [7, 8, 9]]

In [41]:
e

[[4, 6], [7, 9]]

In [42]:
def minors(A):
    lst = []
    for i in np.nditer(A):
        lst.append(i)
    m = np.zeros((3,3))
    for i in range(len(A)):
        for j in range(len(A[i])):
            mat = minor_coef(A,i,j)
            value = (mat[0][0]*mat[1][1] - mat[0][1]*mat[1][0])
            m[[i],[j]] = value
    return m

In [3]:
x = np.array([[1,5,3],[4,5,6],[7,8,9]])

In [6]:
r = np.delete(x,1,0)

In [10]:
x

array([[1, 5, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
def minor_coef(A, i, j):
    return np.delete(np.delete(A,i,0),j,1)

In [11]:
c = minor_coef(x,0,0)

In [12]:
c

array([[5, 6],
       [8, 9]])

In [13]:
y = np.array([[1,5,3],[4,5,6],[7,8,9]])

In [14]:
x*y

array([[ 1, 25,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [15]:
x@y

array([[ 42,  54,  60],
       [ 66,  93,  96],
       [102, 147, 150]])